from raw2processed import Raw2Processed
from Tkinter import *
from ttk import *

class Raw2Attributes(Raw2Processed):

	def get_frame(self, parent):
		f = Frame(parent)
		Label(f, text='attr').pack()
		return f

	def get_value_dict(self):
		'''creates and returns the dictionary of the values of this object.
			these are generated by calling self.get_frame()'''
		return {'a' : 1}